[dependencies]
base = "0.11.1"
xtended-numbers = "0.3.1"

[package]
name = "xtended-text"
version = "0.3.1"
description = "A library for text manipulation"
repository = "https://github.com/edjcase/motoko_text"
keywords = ["text"]
license = "MIT"

[dev-dependencies]
test = "2.0.0"
