[dependencies]
base = "0.9.4"
xtended-numbers = "0.2.1"

[package]
name = "xtended-text"
version = "0.2.3"
description = "A library for text manipulation"
repository = "https://github.com/edjcase/motoko_text"

[dev-dependencies]
test = "1.0.1"